package de.hswt.swa.cryptotool.socket;

public enum ConnectionState {
    CLIENT_CONNECTION_REQUEST,
    CLIENT_CONNECTION_END,
    CLIENT_ENCODE_REQUEST,
    CLIENT_DECODE_REQUEST,
    CLIENT_PLAIN_TEXT_DONE,
    CLIENT_PASSWORD_DONE,
    SERVER_CONNECTION_ACCEPT,
    SERVER_CONNECTION_END,
    SERVER_ENCODE_ACCEPT,
    SERVER_ENCODE_SUCCESS,
    SERVER_ENCODE_FAILURE,
    SERVER_PLAIN_TEXT_REQUEST,
    SERVER_PASSWORD_REQUEST,
    SERVER_CIPHER_REQUEST,
    SERVER_CIPHER_ACCEPT,
    SERVER_DECODE_ACCEPT,
}
